name: Automação Selenium - Windows
on: [push, pull_request]

jobs:
  test-on-windows:
    runs-on: windows-latest
    timeout-minutes: 30  # Aumenta o tempo limite

    steps:
    # Passo 1: Checkout do código
    - name: Checkout repository
      uses: actions/checkout@v4

    # Passo 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'  # Habilita cache de dependências

    # Passo 3: Instalar Chrome e Driver (versão otimizada)
    - name: Install Chrome and Driver
      shell: pwsh
      run: |
        # Instalação mais robusta do Chrome
        $ProgressPreference = 'SilentlyContinue'
        $chromePath = "$env:ProgramFiles\Google\Chrome\Application\chrome.exe"
        
        if (-not (Test-Path $chromePath)) {
          Write-Host "Installing Chrome..."
          Invoke-WebRequest "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/114.0.5735.90/win64/chrome-installer.exe" -OutFile chrome_installer.exe
          Start-Process -FilePath .\chrome_installer.exe -Args "/silent /install" -Wait
          Remove-Item chrome_installer.exe
        }
        
        # Instalação do ChromeDriver compatível
        $chromeVersion = (Get-Item $chromePath).VersionInfo.FileVersion.Split('.')[0]
        $driverUrl = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/114.0.5735.90/win64/chromedriver-win64.zip"
        
        Invoke-WebRequest $driverUrl -OutFile chromedriver.zip
        Expand-Archive -Path chromedriver.zip -DestinationPath . -Force
        $driverPath = (Resolve-Path ".\chromedriver-win64\chromedriver.exe").Path
        echo "::add-path::$((Split-Path $driverPath -Parent))"

    # Passo 4: Instalar dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest pytest-html

    # Passo 5: Executar testes
    - name: Run tests
      run: |
        python -m pytest tests/ -v --html=report.html

    # Passo 6: Upload do relatório (VERSÃO CORRIGIDA)
    - name: Upload test report
      uses: actions/upload-artifact@v4  # Versão atualizada
      with:
        name: windows-test-report
        path: report.html
        if-no-files-found: error  # Falha se não encontrar o relatório