name: Automação Selenium Multiplataforma
on: [push, pull_request]

jobs:
  test-on-windows:
    name: Testes no Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Chrome and Driver
        shell: pwsh
        run: |
          # Seus comandos de instalação do Chrome/Driver
          # ...
          
      - name: Run Tests
        run: |
          python -m pytest tests/ --html=report.html
          
      - uses: actions/upload-artifact@v3
        with:
          name: windows-report
          path: report.html

  test-on-ubuntu:
    name: Testes no Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Chrome and Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          
      - name: Run Tests
        run: |
          python -m pytest tests/ --html=report.html
          
      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu-report
          path: report.html