name: Automação Selenium com Python

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VERSAO_PYTHON: '3.9'
  VERSAO_CHROME: 'latest'

permissions:
  contents: read
  actions: write
  checks: write

jobs:
  testes:
    runs-on: windows-latest  # Executa no Windows

    steps:
    # Passo 1: Baixar o código
    - name: Baixar repositório
      uses: actions/checkout@v3

    # Passo 2: Configurar Python
    - name: Instalar Python ${{ env.VERSAO_PYTHON }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.VERSAO_PYTHON }}

    # Passo 3: Instalar Google Chrome
    - name: Instalar Google Chrome
      shell: pwsh
      run: |
        $instalador = "chrome_installer.exe"
        Write-Output "Baixando o Chrome..."
        Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile $instalador
        
        Write-Output "Instalando o Chrome..."
        Start-Process -FilePath $instalador -Args "/silent /install" -Verb RunAs -Wait
        
        Write-Output "Limpando instalador..."
        Remove-Item $instalador
        
        Write-Output "Versão instalada: $((Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe').'(Default)').VersionInfo.ProductVersion)"

    # Passo 4: Configurar ChromeDriver
    - name: Instalar ChromeDriver
      shell: pwsh
      run: |
        $caminhoChrome = "${env:ProgramFiles}\Google\Chrome\Application\chrome.exe"
        $versaoChrome = (Get-Item $caminhoChrome).VersionInfo.FileVersion.Split('.')[0]
        $urlVersao = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$versaoChrome"
        $versaoDriver = Invoke-RestMethod -Uri $urlVersao
        
        Write-Output "Baixando ChromeDriver versão $versaoDriver"
        Invoke-WebRequest "https://chromedriver.storage.googleapis.com/$versaoDriver/chromedriver_win32.zip" -OutFile "chromedriver.zip"
        Expand-Archive -Path "chromedriver.zip" -DestinationPath "$env:GITHUB_WORKSPACE"
        Add-Content -Path $env:GITHUB_PATH -Value "$env:GITHUB_WORKSPACE"
        
        Write-Output "ChromeDriver instalado com sucesso"

    # Passo 5: Criar ambiente virtual
    - name: Criar ambiente virtual
      shell: pwsh
      run: |
        python -m venv venv
        venv\Scripts\activate
        python -m pip install --upgrade pip

    # Passo 6: Instalar dependências
    - name: Instalar dependências
      shell: pwsh
      run: |
        venv\Scripts\activate
        pip install -r requirements.txt
        pip install pytest pytest-html

    # Passo 7: Executar testes
    - name: Rodar testes
      shell: pwsh
      env:
        USUARIO_SAUCE: ${{ secrets.USUARIO_SAUCE }}
        CHAVE_SAUCE: ${{ secrets.CHAVE_SAUCE }}
      run: |
        venv\Scripts\activate
        python -m pytest tests/ -v --html=relatorio_teste.html

    # Passo 8: Enviar relatório
    - name: Enviar relatório de testes
      uses: actions/upload-artifact@v3
      with:
        name: relatorio-pytest
        path: relatorio_teste.html