name: Automação Selenium - Compra Standard
on: [push, pull_request]

jobs:
  test-on-windows:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Chrome and Driver
      shell: pwsh
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile chrome_installer.exe
        Start-Process -FilePath .\chrome_installer.exe -Args "/silent /install" -Wait
        Remove-Item chrome_installer.exe
        python -m pip install webdriver-manager

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest pytest-html pytest-metadata

    - name: Create pytest configuration
      run: |
        @"
        [pytest]
        addopts = 
            -v
            --html=relatorio_teste.html
            --self-contained-html
            --capture=sys
            --show-capture=log
        metadata =
            Runner: GitHub Actions
            Python: 3.9
            Platform: Windows
        "@ > pytest.ini

    - name: Run tests
      run: |
        python -m pytest test_execution/test_execution_compra_standard.py
        python -m pytest test_execution/test_execution_compra_visual_true.py
        python -m pytest test_execution/test_execution_compra_problem.py
        
    - name: Process and upload report
      shell: pwsh
      run: |
        # Corrige possíveis problemas de encoding
        $content = Get-Content -Path "relatorio_teste.html" -Raw
        $content = $content -replace '<\s*br\s*/?>', '<br>' -replace '<\s*/\s*div\s*>', '</div>'
        $content | Out-File -FilePath "report.html" -Encoding utf8 -Force
        
        if (-not (Test-Path "report.html")) {
          Write-Error "Relatório não foi gerado corretamente!"
          exit 1
        }

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: relatorio-compra-standard
        path: report_compra_standard.html
        if-no-files-found: error